notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

os:
  - linux
  - osx

git:
  depth: 10

branches:
  only:
  - master

env:
  global:
    - AUTHORIZED_BRANCH="master"

script:
  - echo "foobar"

after_success:
  - ./.travis/publish.sh
