notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

os:
  - linux

git:
  depth: 10

branches:
  only:
    - master

script: 'echo "foobar"'

after_success: |
  echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
  echo "TRAVIS_BUILD_DIR: $TRAVIS_BUILD_DIR"
  echo "TRAVIS_BUILD_ID: $TRAVIS_BUILD_ID"
  echo "TRAVIS_BUILD_NUMBER: $TRAVIS_BUILD_NUMBER"
  echo "TRAVIS_COMMIT: $TRAVIS_COMMIT"
  echo "TRAVIS_COMMIT_RANGE: $TRAVIS_COMMIT_RANGE"
  echo "TRAVIS_JOB_ID: $TRAVIS_JOB_ID"
  echo "TRAVIS_JOB_NUMBER: $TRAVIS_JOB_NUMBER"
  echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
  echo "TRAVIS_SECURE_ENV_VARS: $TRAVIS_SECURE_ENV_VARS"
  echo "TRAVIS_REPO_SLUG: $TRAVIS_REPO_SLUG"
  echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
  echo "TRAVIS_TAG: $TRAVIS_TAG"
  cd "$TRAVIS_BUILD_DIR"
  git log --oneline --graph --decorate
  git status
